export const AuthStates = {
	NOT_AUTHORIZED:"NOT_AUTHORIZED",
	IN_PROGRESS:"IN_PROGRESS",
	TOKEN_RECEIVED:"TOKEN_RECEIVED",
	AUTH_CONFIRMED:"AUTH_CONFIRMED"
};

export const AppIds = {
	TWITTER:"TWITTER",
	FACEBOOK:"FACEBOOK",
	MEDIUM:"MEDIUM",
	GOOGLE:"GOOGLE"
}

